parameters:
#    mnu_main.example.class: Mnu\MainBundle\Example

services:
#    mnu_main.example:
#        class: %mnu_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
